const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const seedSubjects=[['Clínica Médica',8,12,'#f59e0b','2026-12-05','AP2'],['Clínica Cirúrgica',6,8,'#e05f5f','2026-12-02','AP2'],['Epidemio Clínica',2,3,'#fde047','2026-11-19','AP2'],['Pato Especial II',3,4,'#60a5fa','2026-12-05','AP2'],['Psiquiatria',3,4,'#f000d8','2026-11-25','AP2'],['Anestesiologia',2,2,'#7c3aed','2026-12-01','AP2'],['Bioquímica Clínica',3,5,'#1d4ed8','','AP2']];
const seedSchedule=[['DOM','08:00',2,'C. MÉDICA','Teoria','Casa'],['SEG','08:00',4,'Cl. Méd - Prática','Prática','HUGV/Adriano Jorge'],['TER','08:00',4,'Cl. Cir - Prática','Prática','HUGV'],['QUA','07:00',4,'Clínica Médica','Teoria','Anexo'],['QUI','15:00',2,'Anestesiologia','Teoria','Anexo'],['SEX','15:00',2,'C. MÉDICA','Questões','Casa'],['SAB','07:00',2,'C. CIRURG','Teoria','Casa']];
const seedTopics=[['Clínica Médica','Insuficiência cardíaca','🟥 Muito cobrado','Médio','Alto'],['Clínica Médica','ECG e dor torácica','🟥 Muito cobrado','Médio','Alto'],['Anestesiologia','Via aérea e RCP','🟥 Muito cobrado','Médio','Alto'],['Anestesiologia','Anestésicos locais','🟧 Cobrado','Médio','Alto'],['Psiquiatria','Transtornos do humor','🟥 Muito cobrado','Médio','Alto'],['Pato Especial II','Tireoide e linfomas','🟥 Muito cobrado','Médio','Alto']];
let subjects=store.get('subjects',seedSubjects.map((s,i)=>({id:Date.now()+i,name:s[0],weight:s[1],goal:s[2],color:s[3],exam:s[4],mode:s[5]})));
let schedule=store.get('schedule',seedSchedule.map((s,i)=>({id:Date.now()+100+i,day:s[0],time:s[1],duration:s[2],activity:s[3],type:s[4],place:s[5]})));
let reviews=store.get('reviews',[]),tasks=store.get('tasks',[]),topics=store.get('topics',seedTopics.map((t,i)=>({id:Date.now()+200+i,subject:t[0],name:t[1],temp:t[2],difficulty:t[3],benefit:t[4],done:false}))),sessions=store.get('sessions',[]);
let reviewMode='all',examMode=store.get('examMode',false);
function today(){return new Date().toISOString().slice(0,10)} function addDays(date,days){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)} function brDate(d){return d?d.split('-').reverse().join('/'):''}
function save(){store.set('subjects',subjects);store.set('schedule',schedule);store.set('reviews',reviews);store.set('tasks',tasks);store.set('topics',topics);store.set('sessions',sessions);store.set('examMode',examMode);renderAll()}
function pct(done,total){return total?Math.round(done/total*100):0} function scoreTopic(t){let temp={'🟥 Muito cobrado':4,'🟧 Cobrado':3,'🟨 Ocasional':2,'🟩 Raro':1}[t.temp]||1;let diff={Fácil:3,Médio:2,Difícil:1}[t.difficulty]||1;let ben={Alto:3,Médio:2,Baixo:1}[t.benefit]||1;return temp*10+diff*3+ben*5}
function addXP(){let xp=reviews.filter(r=>r.done).length*20+tasks.filter(t=>t.done).length*15+topics.filter(t=>t.done).length*25+sessions.reduce((a,s)=>a+(s.correct/s.done>=.8?50:25),0);let level=Math.floor(xp/100)+1;$('#xp').textContent=xp;$('#level').textContent=level;$('#xpBar').style.width=(xp%100)+'%'}
function initTabs(){ $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')})}
function renderSchedule(){const days=['DOM','SEG','TER','QUA','QUI','SEX','SAB'];let html='<tr><th>Dia</th><th>Horário</th><th>Duração</th><th>Atividade</th><th>Tipo</th><th>Local</th><th></th></tr>';schedule.sort((a,b)=>days.indexOf(a.day)-days.indexOf(b.day)||a.time.localeCompare(b.time)).forEach(x=>html+=`<tr><td><span class="badge">${x.day}</span></td><td>${x.time}</td><td>${x.duration||1}h</td><td><strong>${x.activity}</strong></td><td>${x.type}</td><td>${x.place||''}</td><td><button class="iconbtn" onclick="delSchedule(${x.id})">🗑️</button></td></tr>`);$('#scheduleTable').innerHTML=html}
function renderSubjects(){let box=$('#subjectCards');box.innerHTML=subjects.map(s=>{let rel=[...reviews.filter(r=>r.subject.toLowerCase()==s.name.toLowerCase()),...tasks.filter(t=>t.subject.toLowerCase()==s.name.toLowerCase()),...topics.filter(t=>t.subject.toLowerCase()==s.name.toLowerCase())];let done=rel.filter(x=>x.done).length;let p=pct(done,rel.length);let days=s.exam?Math.ceil((new Date(s.exam)-new Date(today()))/86400000):null;return `<div class="subject-card" style="--c:${s.color}"><h3>${s.name}</h3><p>Peso <strong>${s.weight}</strong> · Meta <strong>${s.goal}h/sem</strong> · ${s.mode}</p><p>${s.exam?`Prova: <strong>${brDate(s.exam)}</strong> ${days!==null?`· ${days} dias`:''}`:'Sem data de prova'}</p><div class="progress"><span style="width:${p}%"></span></div><p><strong>${p}%</strong> concluído</p><button class="iconbtn" onclick="delSubject(${s.id})">🗑️ Remover</button></div>`}).join('')||$('#emptyState').innerHTML}
function renderTopics(){let list=[...topics].sort((a,b)=>scoreTopic(b)-scoreTopic(a));let html='<tr><th>Check</th><th>Ordem</th><th>Disciplina</th><th>Tópico</th><th>Temperatura</th><th>Dificuldade</th><th>Custo-benefício</th><th></th></tr>';list.forEach((t,i)=>html+=`<tr class="${t.done?'done-row':''}"><td><input class="check" type="checkbox" ${t.done?'checked':''} onchange="toggleTopic(${t.id})"></td><td><span class="badge">#${i+1}</span></td><td>${t.subject}</td><td><strong>${t.name}</strong></td><td>${t.temp}</td><td>${t.difficulty}</td><td>${t.benefit}</td><td><button class="iconbtn" onclick="delTopic(${t.id})">🗑️</button></td></tr>`);$('#topicTable').innerHTML=html}
function renderReviews(){let f=$('#reviewFilter').value?.toLowerCase()||'';let list=reviews.filter(r=>reviewMode==='today'?r.date===today()&&!r.done:reviewMode==='late'?r.date<today()&&!r.done:true).filter(r=>(r.subject+r.topic+r.date+r.stage).toLowerCase().includes(f));let html='<tr><th>Check</th><th>Data</th><th>Etapa</th><th>Disciplina</th><th>Tópico</th><th>Tipo</th><th>Prioridade</th><th></th></tr>';list.sort((a,b)=>a.date.localeCompare(b.date)).forEach(r=>html+=`<tr class="${r.done?'done-row':''}"><td><input class="check" type="checkbox" ${r.done?'checked':''} onchange="toggleReview(${r.id})"></td><td>${brDate(r.date)}</td><td><span class="badge">${r.stage}</span></td><td>${r.subject}</td><td>${r.topic}</td><td>${r.kind||'Revisão'}</td><td class="${r.priority==='Alta'?'priority-high':''}">${r.priority}</td><td><button class="iconbtn" onclick="delReview(${r.id})">🗑️</button></td></tr>`);$('#reviewTable').innerHTML=html}
function renderToday(){let list=reviews.filter(r=>!r.done&&r.date<=today()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,8);$('#todayList').innerHTML=list.map(r=>`<div class="compact-item"><div><strong>${r.subject}</strong><br><span>${r.stage} · ${r.topic} · ${brDate(r.date)}</span></div><input class="check" type="checkbox" onchange="toggleReview(${r.id})"></div>`).join('')||'<div class="empty">Nenhuma revisão pendente hoje.</div>'}
function renderTasks(){let html=tasks.sort((a,b)=>a.date.localeCompare(b.date)).map(t=>`<div class="task ${t.done?'done':''}"><div><strong>${t.title}</strong><br><span>${t.subject} · ${t.kind} · ${brDate(t.date)}</span></div><div><input class="check" type="checkbox" ${t.done?'checked':''} onchange="toggleTask(${t.id})"> <button class="iconbtn" onclick="delTask(${t.id})">🗑️</button></div></div>`).join('');$('#taskList').innerHTML=html||$('#emptyState').innerHTML}
function renderProgress(){let area=$('#progressArea');area.innerHTML=subjects.map(s=>{let rel=[...reviews.filter(r=>r.subject.toLowerCase()==s.name.toLowerCase()),...tasks.filter(t=>t.subject.toLowerCase()==s.name.toLowerCase()),...topics.filter(t=>t.subject.toLowerCase()==s.name.toLowerCase())];let done=rel.filter(x=>x.done).length;let p=pct(done,rel.length);return `<div class="progress-row"><strong>${s.name}</strong><div class="progress"><span style="width:${p}%"></span></div><small>${done}/${rel.length} itens concluídos · ${p}%</small></div>`}).join('')}
function renderCampaign(){let map=$('#campaignMap');map.innerHTML=subjects.map(s=>{let ts=topics.filter(t=>t.subject.toLowerCase()==s.name.toLowerCase()).sort((a,b)=>scoreTopic(b)-scoreTopic(a));let done=ts.filter(t=>t.done).length;return `<div class="node"><h3>${s.name}</h3><p>${done}/${ts.length} fases concluídas</p><ul>${ts.map(t=>`<li>${t.done?'✅':'⬜'} ${t.name}</li>`).join('')||'<li>Cadastre tópicos no Pareto</li>'}</ul><strong>${ts.length&&done===ts.length?'🏆 Chefe liberado':'🔒 Chefe bloqueado'}</strong></div>`}).join('')}
function renderQuestions(){let html='<tr><th>Data</th><th>Disciplina</th><th>Tópico</th><th>Tipo</th><th>Questões</th><th>Acertos</th><th>%</th><th></th></tr>';sessions.sort((a,b)=>b.date.localeCompare(a.date)).forEach(s=>html+=`<tr><td>${brDate(s.date)}</td><td>${s.subject}</td><td>${s.topic}</td><td>${s.kind}</td><td>${s.done}</td><td>${s.correct}</td><td><strong>${Math.round(s.correct/s.done*100)}%</strong></td><td><button class="iconbtn" onclick="delSession(${s.id})">🗑️</button></td></tr>`);$('#questionTable').innerHTML=html;let weak=[...sessions].sort((a,b)=>(a.correct/a.done)-(b.correct/b.done)).slice(0,3);$('#weaknessBox').innerHTML=weak.map(s=>`<div class="subject-card" style="--c:${(s.correct/s.done)<.6?'#dc2626':'#f59e0b'}"><h3>${s.topic}</h3><p>${s.subject}</p><div class="progress"><span style="width:${Math.round(s.correct/s.done*100)}%"></span></div><p>${Math.round(s.correct/s.done*100)}% de acerto</p></div>`).join('')||'<div class="empty">Registre sessões para ver pontos fracos.</div>'}
function renderStats(){let done=reviews.filter(r=>r.done).length+tasks.filter(t=>t.done).length+topics.filter(t=>t.done).length;let total=reviews.length+tasks.length+topics.length;$('#weeklyHours').textContent=schedule.reduce((a,s)=>a+(+s.duration||1),0)+'h';$('#todayReviewsCount').textContent=reviews.filter(r=>!r.done&&r.date===today()).length;$('#lateReviewsCount').textContent=reviews.filter(r=>!r.done&&r.date<today()).length;$('#overallProgress').textContent=pct(done,total)+'%';document.body.classList.toggle('exam-banner',examMode);addXP()}
function renderAll(){renderSchedule();renderSubjects();renderTopics();renderReviews();renderToday();renderTasks();renderProgress();renderCampaign();renderQuestions();renderStats()}
window.delSchedule=id=>{schedule=schedule.filter(x=>x.id!==id);save()};window.delSubject=id=>{subjects=subjects.filter(x=>x.id!==id);save()};window.delReview=id=>{reviews=reviews.filter(x=>x.id!==id);save()};window.delTask=id=>{tasks=tasks.filter(x=>x.id!==id);save()};window.delTopic=id=>{topics=topics.filter(x=>x.id!==id);save()};window.delSession=id=>{sessions=sessions.filter(x=>x.id!==id);save()};
window.toggleReview=id=>{reviews=reviews.map(x=>x.id===id?{...x,done:!x.done}:x);save()};window.toggleTask=id=>{tasks=tasks.map(x=>x.id===id?{...x,done:!x.done}:x);save()};window.toggleTopic=id=>{topics=topics.map(x=>x.id===id?{...x,done:!x.done}:x);save()};
$('#addSchedule').onclick=()=>{schedule.push({id:Date.now(),day:$('#day').value,time:$('#time').value,duration:+$('#duration').value||1,activity:$('#activity').value||'Estudo',type:$('#type').value,place:$('#place').value});save();$('#scheduleForm').reset()};
$('#addSubject').onclick=()=>{subjects.push({id:Date.now(),name:$('#subjectName').value||'Nova disciplina',weight:+$('#subjectWeight').value||1,goal:+$('#subjectGoal').value||1,exam:$('#examDate').value,mode:$('#subjectMode').value,color:$('#subjectColor').value});save();$('#subjectForm').reset()};
function addTopic(){topics.push({id:Date.now(),subject:$('#topicSubject').value||'Geral',name:$('#topicName').value||'Novo tópico',temp:$('#topicTemp').value,difficulty:$('#topicDifficulty').value,benefit:$('#topicBenefit').value,done:false});save();$('#topicForm').reset()} $('#addTopic').onclick=addTopic; $('#addTopicInline').onclick=addTopic;
$('#addReview').onclick=()=>{let subject=$('#reviewSubject').value||'Disciplina',topic=$('#reviewTopic').value||'Assunto',date=$('#reviewDate').value||today(),priority=$('#reviewPriority').value,kind=$('#reviewKind').value;[['Estudei',0],['R1',1],['R2',3],['R3',7],['R4',14],['R5',30]].forEach(([stage,days],i)=>reviews.push({id:Date.now()+i,subject,topic,date:addDays(date,days),priority,kind,stage,done:false}));save();$('#reviewForm').reset();$('#reviewDate').value=today()};
$('#addTask').onclick=()=>{tasks.push({id:Date.now(),title:$('#taskTitle').value||'Nova tarefa',subject:$('#taskSubject').value||'Geral',date:$('#taskDate').value||today(),kind:$('#taskKind').value,done:false});save();$('#taskForm').reset();$('#taskDate').value=today()};
$('#addQuestionSession').onclick=()=>{let done=+$('#qDone').value||1,correct=Math.min(+$('#qCorrect').value||0,done);sessions.push({id:Date.now(),subject:$('#qSubject').value||'Geral',topic:$('#qTopic').value||'Tópico',done,correct,kind:$('#qKind').value,date:$('#qDate').value||today()});save();$('#questionForm').reset();$('#qDate').value=today()};
$('#reviewFilter').oninput=renderReviews;$('#todayReviews').onclick=()=>{reviewMode='today';renderReviews()};$('#lateReviews').onclick=()=>{reviewMode='late';renderReviews()};$('#allReviews').onclick=()=>{reviewMode='all';renderReviews()};$('#buildCampaign').onclick=renderCampaign;
$('#darkToggle').onclick=()=>{document.body.classList.toggle('dark');store.set('dark',document.body.classList.contains('dark'))};$('#examMode').onclick=()=>{examMode=!examMode;alert(examMode?'Modo pré-prova ativado: priorize 70% questões, 20% revisão, 10% teoria.':'Modo pré-prova desativado.');save()};$('#resetData').onclick=()=>{if(confirm('Apagar todos os dados salvos neste navegador?')){localStorage.clear();location.reload()}};
if(store.get('dark',false))document.body.classList.add('dark');['reviewDate','taskDate','qDate'].forEach(id=>$('#'+id).value=today());initTabs();renderAll();
